### ISSUE TITLE
result_interpretation.py file is missing

### ISSUE THREAD

**Issue by chhatrapalsinhzala** [bgarcia7/ai_trainer#1]
i have converted the  project into python 3 and it shows me an ImportError that result_interpretation.py  is missing

Error Log: 

Traceback (most recent call last):
  File "server.py", line 7, in <module>
    from ai_trainer import Personal_Trainer
  File "D:\project\ai_trainer-master\ai_trainer-master\ai_trainer.py", line 19, in <module>
    import result_interpretation as advice
ImportError: bad magic number in 'result_interpretation': b'\x03\xf3\r\n'

**Comment by sattyamjjain** [comment]
Want the result_interpretation.py file

Traceback (most recent call last):
  File "server.py", line 7, in <module>
    from ai_trainer import Personal_Trainer
  File "E:\ai_trainer\ai_trainer.py", line 19, in <module>
    import result_interpretation as advice
ImportError: bad magic number in 'result_interpretation': b'\x03\xf3\r\n'
